// <auto-generated />
using System;
using AssistLK.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AssistLK.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260912162153_AddComponent4TrackingEntities")]
    partial class AddComponent4TrackingEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AssistLK.Domain.Entities.Complaint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ComplainantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceJobId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("AssistLK.Domain.Entities.CompletionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AdditionalCost")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProofOfWorkImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceJobId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceJobId")
                        .IsUnique();

                    b.ToTable("CompletionRecords");
                });

            modelBuilder.Entity("AssistLK.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceJobId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceJobId")
                        .IsUnique();

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("AssistLK.Domain.Entities.ServiceJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ServiceJobs");
                });

            modelBuilder.Entity("AssistLK.Domain.Entities.ServiceStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("OldStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceJobId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceJobId");

                    b.ToTable("ServiceStatusHistories");
                });

            modelBuilder.Entity("AssistLK.Domain.Entities.Complaint", b =>
                {
                    b.HasOne("AssistLK.Domain.Entities.ServiceJob", null)
                        .WithMany("Complaints")
                        .HasForeignKey("ServiceJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistLK.Domain.Entities.CompletionRecord", b =>
                {
                    b.HasOne("AssistLK.Domain.Entities.ServiceJob", null)
                        .WithOne("CompletionRecord")
                        .HasForeignKey("AssistLK.Domain.Entities.CompletionRecord", "ServiceJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistLK.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("AssistLK.Domain.Entities.ServiceJob", null)
                        .WithOne("Feedback")
                        .HasForeignKey("AssistLK.Domain.Entities.Feedback", "ServiceJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistLK.Domain.Entities.ServiceStatusHistory", b =>
                {
                    b.HasOne("AssistLK.Domain.Entities.ServiceJob", null)
                        .WithMany("StatusHistories")
                        .HasForeignKey("ServiceJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssistLK.Domain.Entities.ServiceJob", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("CompletionRecord");

                    b.Navigation("Feedback");

                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
