"""Input request schemas matching the .NET ProblemUnderstandingInput contract."""
from datetime import datetime
from typing import Any
from uuid import UUID
from pydantic import BaseModel, ConfigDict, Field


class ClarificationHistoryItemDto(BaseModel):
    """Customer-supplied clarification history from past rounds."""

    model_config = ConfigDict(populate_by_name=True)

    round: int = Field(ge=1, description="Clarification round number (1 or 2).")
    question: str = Field(
        min_length=1,
        max_length=500,
        description="Follow-up question previously asked to the customer.",
    )
    answer: str = Field(
        min_length=1,
        max_length=1000,
        description="Customer-provided response text.",
    )


class ProblemUnderstandingInputDto(BaseModel):
    """Mirror of .NET ProblemUnderstandingInput domain contract."""

    model_config = ConfigDict(populate_by_name=True)

    service_request_id: UUID = Field(
        alias="serviceRequestId",
        description="Unique identifier of the ServiceRequest being analysed.",
    )
    description: str = Field(
        min_length=1,
        max_length=2000,
        description="Customer's natural-language description of their problem.",
    )
    location_text: str | None = Field(
        default=None,
        alias="locationText",
        max_length=500,
        description="Human-readable location text supplied by the customer.",
    )
    latitude: float | None = Field(
        default=None,
        ge=-90.0,
        le=90.0,
        description="Optional GPS latitude coordinate (-90 to 90).",
    )
    longitude: float | None = Field(
        default=None,
        ge=-180.0,
        le=180.0,
        description="Optional GPS longitude coordinate (-180 to 180).",
    )
    category_hint: str | None = Field(
        default=None,
        alias="categoryHint",
        max_length=100,
        description="Optional customer category preference (non-authoritative prior belief).",
    )
    clarification_history: list[ClarificationHistoryItemDto] = Field(
        default_factory=list,
        alias="clarificationHistory",
        description="Historical clarification rounds and answers provided by the customer.",
    )


class AgentExecutionRequest(BaseModel):
    """Standardized internal agent execution wire request specification."""

    model_config = ConfigDict(populate_by_name=True)

    request_id: UUID = Field(
        alias="requestId",
        description="Unique correlation ID generated by .NET for tracing across services.",
    )
    agent_name: str = Field(
        default="ProblemUnderstandingAgent",
        alias="agentName",
        description="Canonical identifier of the target agent.",
    )
    operation: str = Field(
        default="analyze-problem",
        description="Specific action requested.",
    )
    timestamp: datetime | None = Field(
        default=None,
        description="UTC timestamp of request dispatch.",
    )
    parameters: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional execution parameters.",
    )
    input: ProblemUnderstandingInputDto = Field(
        description="Strongly-typed problem understanding input payload.",
    )
